[package]
name = "chat-app"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = { version = "0.4.42", features = ["serde"] }
axum = { version = "0.8.6", features = ["macros"] }
tokio = { version = "1.12", features = ["full"] }
futures = "0.3.6"
uuid = { version = "1.18", features = ["serde"] }
bigdecimal = "0.4"
num-bigint = "0.4"
tracing = "0.1.36"
tracing-subscriber = { version = "0.3.14", features = ["env-filter"] }
anyhow = "1.0.100"
serde = { version = "1.0.100", features = ["derive"] }
thiserror = "2.0.17"
scylla = { version = "1.4.1", features = ["chrono-04"] }
axum-anyhow = "0.7.4"
